# Generated by Django 3.2 on 2021-05-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210527_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('age', models.IntegerField()),
                ('source', models.CharField(max_length=122)),
                ('destination', models.CharField(max_length=122)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
