# Generated by Django 3.2.4 on 2021-06-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210531_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aadhar_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
