# Generated by Django 3.2.4 on 2021-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_aadhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='Seat',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
    ]
