# Generated by Django 3.2.4 on 2021-06-05 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210605_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Address',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
