# Generated by Django 3.2.3 on 2021-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mobile_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
